### ISSUE TITLE
http code: 431 error while reading data from salesforce account table

### ISSUE THREAD

**Issue by KANAK-G** [turbot/steampipe-plugin-salesforce#46] opened 2024-01-16 06:50 UTC
**Describe the bug**
Salesforce account object has 754 columns with 730 custom columns and the rest are default columns. While fetching data from this object getting 431 error.

**Steampipe version (`steampipe -v`)**
v0.21.2

**Plugin version (`steampipe plugin list`)**
v0.7

**To reproduce**
Pass the credentials in the config file

**Expected behavior**
Should be queryable

**Additional context**
No

**Comment by ParthaI** [comment] 2024-01-16 14:48
Hello @KANAK-G, Thanks for raising the issue, and I'm sorry to see that you are running into the issues.

I was having a look into the issue. I have a custom salesforce table named `salesforce_api__c`, which contains nearly `10,422`  rows with `28` columns.
While I am querying this table, I can get the result successfully.

As per the error code mentioned in the issue description(`431`), I believe it is due to [Request Header Fields Too Large](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431).

Could you please share more details on how you are using the tables? What is the query you are running? Which will help us reproduce/debug the issue.

Also, could you please try fetching one or two columns from that table for which you are getting the `431` error, if you are still getting the error or not?

Thanks!

**Comment by KANAK-G** [comment] 2024-01-17 06:24
Hello @ParthaI, thank you for promptly addressing this issue.

I'm also successfully retrieving data from all my custom objects. However, I'm encountering an issue with the static table 'salesforce_account.' I could query it before, but there was a schema change.

Is there a workaround or solution to overcome this issue?

I'm providing credentials in the config as per the documentation, and when attempting to query through the terminal using
 select * from salesforce_account limit 10, I'm facing an error. 

I've also tried queries with 1-2 columns, but the error persists.

**Comment by ParthaI** [comment] 2024-01-17 14:14
Hello @KANAK-G, thank you for providing the information.

Currently, I'm unable to reproduce the error on my end when querying the `salesforce_account` table, as it consistently returns results for me. To further investigate this issue, I have a few questions:

1. Is this error specific to the `salesforce_account` table, or have you encountered it with other tables too?
2. Regarding the `salesforce_account` table, does this error occur every time you query it, or do you sometimes receive results?
3. Could you please provide the log details found in `~/.steampipe/logs/plugin-2024-01-1*.log`? Before sharing, ensure any sensitive information is redacted.
4. It would also be helpful if you could share the `.spc` file for the Salesforce plugin, with sensitive information removed.

Your responses to these queries will be invaluable in resolving this issue. Thank you!

**Comment by KANAK-G** [comment] 2024-01-17 16:11
Hi @ParthaI ,
1. No, I'm not encountering this error with other tables.
2. No, it's occurring each time and I have not received any results so far.
3. `2024-01-17 11:39:36.302 UTC [109755] LOG:  connection received: host=127.0.0.1 port=52558
2024-01-17 11:39:36.306 UTC [109755] LOG:  connection authorized: user=steampipe database=steampipe application_name=steampipe_client_system_fee2 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-17 11:39:36.309 UTC [109676] LOG:  could not receive data from client: Connection reset by peer
2024-01-17 11:39:36.309 UTC [109677] LOG:  could not receive data from client: Connection reset by peer
2024-01-17 11:39:36.309 UTC [109676] LOG:  disconnection: session time: 0:00:08.401 user=root database=steampipe host=127.0.0.1 port=52528
2024-01-17 11:39:36.309 UTC [109677] LOG:  disconnection: session time: 0:00:08.390 user=root database=steampipe host=127.0.0.1 port=52534
2024-01-17 11:39:41.156 UTC [WARN]  hub: stream receive error rpc error: code = Unknown desc = sfcrmuat: [simpleforce] Error. http code: 431 Error Message:   Error Code:  (0xc000bfe000)
2024-01-17 11:39:41.156 UTC [109753] ERROR:  rpc error: code = Unknown desc = sfcrmuat: [simpleforce] Error. http code: 431 Error Message:   Error Code: 
2024-01-17 11:39:41.156 UTC [109753] STATEMENT:  select * from salesforce_account limit 10
2024-01-17 11:40:18.779 UTC [WARN]  hub: stream receive error rpc error: code = Unknown desc = sfcrmuat: [simpleforce] Error. http code: 431 Error Message:   Error Code:  (0xc000bfe0c0)
2024-01-17 11:40:18.779 UTC [109753] ERROR:  rpc error: code = Unknown desc = sfcrmuat: [simpleforce] Error. http code: 431 Error Message:   Error Code: 
2024-01-17 11:40:18.779 UTC [109753] STATEMENT:  select * from salesforce_account limit 10
2024-01-17 11:40:28.105 UTC [WARN]  hub: stream receive error rpc error: code = Unknown desc = sfcrmuat: [simpleforce] Error. http code: 431 Error Message:   Error Code:  (0xc000bfe180)
2024-01-17 11:40:28.106 UTC [109753] ERROR:  rpc error: code = Unknown desc = sfcrmuat: [simpleforce] Error. http code: 431 Error Message:   Error Code: 
2024-01-17 11:40:28.106 UTC [109753] STATEMENT:  select * from salesforce_account limit 10
2024-01-17 11:41:27.960 UTC [109687] LOG:  disconnection: session time: 0:01:59.999 user=root database=steampipe host=127.0.0.1 port=52538
2024-01-17 15:55:14.909 UTC [WARN]  hub: stream receive error rpc error: code = Unknown desc = sfcrmuat: [simpleforce] Error. http code: 431 Error Message:   Error Code:  (0xc000bfe300)
2024-01-17 15:55:14.909 UTC [109753] ERROR:  rpc error: code = Unknown desc = sfcrmuat: [simpleforce] Error. http code: 431 Error Message:   Error Code: 
2024-01-17 15:55:14.909 UTC [109753] STATEMENT:  select * from salesforce_account limit 10`

4. `connection "sfcrmuat" {
  plugin = "salesforce"
  url = "xxxxxxx"
  username = "xxxxxx"
  password = "xxxxxxx"
  token = "xxxxxxx"
  objects = ["UserRole","User","Proposal_WorkOrder__c","Product_Deal_Detail__c","Opportunity_WorkOrder__c","Opportunity_Objective__c", "Case","Proposal__c","Product_Deal__c", "Workorder","Proposal_item__c"]}`

**Comment by bigdatasourav** [comment] 2024-04-09 04:08
Hey @KANAK-G, we have tried to reproduce the above error but failed to do so, an HTTP 431 error indicates that the request header fields are too large. This can happen if the Salesforce API request includes too much data in the headers, possibly due to a large set of columns requested.

https://salesforce.stackexchange.com/questions/310014/how-to-fix-error-431-request-header-fields-too-large-http-code431-in-anonymo

Could you please try [these](https://hub.steampipe.io/plugins/turbot/salesforce/tables/salesforce_account#examples) queries and let us know if they are working?

**Comment by bigdatasourav** [comment] 2024-04-09 06:24
This [PR](https://github.com/turbot/steampipe-plugin-salesforce/pull/52) may solve the above problem.

**Comment by bigdatasourav** [comment] 2024-04-15 12:07
@KANAK-G,closing this issue for now as we haven't received further feedback. The above PR might resolve the problem. Please feel free to reopen this issue if you have any more to share or if the issue persists. Thank you!

**Closed by bigdatasourav** 2024-04-15 12:07 UTC
Labels: bug
